debug: true

spring:
  application:
    name: spring-boot-skeleton-web
  datasource:
    platform: all
#    schema
#    1. h2 일때는 동작함 하지만 mariadb 일 때는 동작 안함
#    2. flyway 사용시에는 동시 사용불가능
#    schema: classpath:import.sql
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      minimum-idle: 5
      maximum-pool-size: 10
      max-lifetime: 3597000
      pool-name: datasource-skeleton-boot-web
#      DB 변경시 log4jdbc.log4j2.properties 도 log4jdbc.drivers 변경이 필요함
#      username: ${user}
#      password: ${password}
#      jdbc-url: jdbc:log4jdbc:mariadb://${host}:3306/crom
      jdbc-url: jdbc:log4jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      data-source-properties:
        cache-prep-stmts: "true"
        prep-stmt-cache-size: "250"
        prep-stmt-cache-sql-limit: "2048"
        use-server-prep-stmts: "true"
        use-local-session-state: "true"
        rewrite-batched-statements: "true"
        cache-result-set-metadata: "true"
        cache-server-configuration: "true"
        elide-set-auto-commits: "true"
        maintain-time-stats: "false"
  thymeleaf:
    #https://docs.spring.io/spring-boot/docs/current/reference/html/howto-hotswapping.html
    cache: false
  devtools:
    restart:
      enabled: true
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
  output:
    ansi:
      enabled: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

jasypt:
  encryptor:
    password: security-key-181218

mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  path: ./log
#  pattern:
#    console: '%-24.24d [%5p] %50.50C (%file:%line\) - %m%n'
#    file: '%-24.24d [%5p] %50.50C (%file:%line\) - %m%n'
  level:
    sample.jsp: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
server:
  ssl:
    key-store: classpath:zzizily.jks
    key-store-password: ${server_ssl_key-store-password}
    key-password: ${server_ssl_key-password}
  http2:
    enabled: true
  port: 8443
